// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogdb

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	IsFeatured    bool
}
