// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package catalogdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProductByID = `-- name: GetProductByID :one
SELECT
    id, name, description, price_cents, image_url,
    manufacturer, crew_amount, max_speed, category,
    stock_quantity, is_active, is_featured, created_at, updated_at
FROM products
WHERE id = $1 AND is_active = true
`

type GetProductByIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	IsFeatured    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.ImageUrl,
		&i.Manufacturer,
		&i.CrewAmount,
		&i.MaxSpeed,
		&i.Category,
		&i.StockQuantity,
		&i.IsActive,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
    name, description, price_cents, image_url,
    manufacturer, crew_amount, max_speed, category,
    stock_quantity, is_active, is_featured
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, name, description, price_cents, image_url,
    manufacturer, crew_amount, max_speed, category,
    stock_quantity, is_active, is_featured, created_at, updated_at
`

type InsertProductParams struct {
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	IsFeatured    bool
}

type InsertProductRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	IsFeatured    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.ImageUrl,
		arg.Manufacturer,
		arg.CrewAmount,
		arg.MaxSpeed,
		arg.Category,
		arg.StockQuantity,
		arg.IsActive,
		arg.IsFeatured,
	)
	var i InsertProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.ImageUrl,
		&i.Manufacturer,
		&i.CrewAmount,
		&i.MaxSpeed,
		&i.Category,
		&i.StockQuantity,
		&i.IsActive,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT
    id, name, description, price_cents, image_url,
    manufacturer, crew_amount, max_speed, category,
    stock_quantity, is_active, is_featured, created_at, updated_at
FROM products
WHERE is_active = true
ORDER BY created_at DESC
`

type ListActiveProductsRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	IsFeatured    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListActiveProducts(ctx context.Context) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsRow
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Manufacturer,
			&i.CrewAmount,
			&i.MaxSpeed,
			&i.Category,
			&i.StockQuantity,
			&i.IsActive,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT
    id, name, description, price_cents, image_url,
    manufacturer, crew_amount, max_speed, category,
    stock_quantity, is_active, is_featured, created_at, updated_at
FROM products
WHERE is_active = true AND is_featured = true
ORDER BY created_at DESC
LIMIT $1
`

type ListFeaturedProductsRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	IsFeatured    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int32) ([]ListFeaturedProductsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturedProductsRow
	for rows.Next() {
		var i ListFeaturedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Manufacturer,
			&i.CrewAmount,
			&i.MaxSpeed,
			&i.Category,
			&i.StockQuantity,
			&i.IsActive,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateProducts = `-- name: TruncateProducts :exec
TRUNCATE products
`

func (q *Queries) TruncateProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateProducts)
	return err
}
