run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - errorlint

issues:
  exclude-files:
    - "internal/catalog/db/db.go"
    - "internal/catalog/db/models.go"
    - "internal/catalog/db/queries.sql.go"
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - errcheck
