// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cartdb

import (
	"time"

	"github.com/google/uuid"
)

type CartItem struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	ImageUrl      *string
	Manufacturer  *string
	CrewAmount    *int32
	MaxSpeed      *string
	Category      string
	StockQuantity int32
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	IsFeatured    bool
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
