// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cartdb

import (
	"context"

	"github.com/google/uuid"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE user_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.UserID, arg.ProductID)
	return err
}

const getCartItemQuantity = `-- name: GetCartItemQuantity :one
SELECT quantity
FROM cart_items
WHERE user_id = $1 AND product_id = $2
`

type GetCartItemQuantityParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItemQuantity(ctx context.Context, arg GetCartItemQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCartItemQuantity, arg.UserID, arg.ProductID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT
    ci.product_id,
    p.name,
    p.price_cents,
    p.image_url,
    ci.quantity,
    p.stock_quantity
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.user_id = $1 AND p.is_active = true
ORDER BY ci.created_at ASC
`

type GetCartItemsRow struct {
	ProductID     uuid.UUID
	Name          string
	PriceCents    int64
	ImageUrl      *string
	Quantity      int32
	StockQuantity int32
}

func (q *Queries) GetCartItems(ctx context.Context, userID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Quantity,
			&i.StockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductForCart = `-- name: GetProductForCart :one
SELECT id, name, price_cents, image_url, stock_quantity, is_active
FROM products
WHERE id = $1
`

type GetProductForCartRow struct {
	ID            uuid.UUID
	Name          string
	PriceCents    int64
	ImageUrl      *string
	StockQuantity int32
	IsActive      bool
}

func (q *Queries) GetProductForCart(ctx context.Context, id uuid.UUID) (GetProductForCartRow, error) {
	row := q.db.QueryRow(ctx, getProductForCart, id)
	var i GetProductForCartRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StockQuantity,
		&i.IsActive,
	)
	return i, err
}

const lockProductForCart = `-- name: LockProductForCart :one
SELECT id, name, price_cents, image_url, stock_quantity, is_active
FROM products
WHERE id = $1
FOR UPDATE
`

type LockProductForCartRow struct {
	ID            uuid.UUID
	Name          string
	PriceCents    int64
	ImageUrl      *string
	StockQuantity int32
	IsActive      bool
}

// LockProductForCart selects the product row with FOR UPDATE so concurrent
// cart writers serialize on the product. Used inside cart Add/Set/Merge
// transactions to make the read-then-clamp-then-write sequence race-free.
func (q *Queries) LockProductForCart(ctx context.Context, id uuid.UUID) (LockProductForCartRow, error) {
	row := q.db.QueryRow(ctx, lockProductForCart, id)
	var i LockProductForCartRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StockQuantity,
		&i.IsActive,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (user_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, product_id) DO UPDATE
    SET quantity   = EXCLUDED.quantity,
        updated_at = now()
RETURNING user_id, product_id, quantity
`

type UpsertCartItemParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type UpsertCartItemRow struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (UpsertCartItemRow, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.UserID, arg.ProductID, arg.Quantity)
	var i UpsertCartItemRow
	err := row.Scan(&i.UserID, &i.ProductID, &i.Quantity)
	return i, err
}
