// Package server builds the Huma API, registers platform endpoints, and applies middleware.
package server

import (
	"context"
	"log/slog"
	"net/http"
	"slices"
	"strings"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
	"github.com/google/uuid"
)

// reqIDKey is the per-request context.Value key holding the request ID
// generated by requestLogMiddleware.
type reqIDKey struct{}

// RequestID extracts the request ID set by requestLogMiddleware, or an empty
// string if the middleware did not run.
func RequestID(ctx context.Context) string {
	if id, ok := ctx.Value(reqIDKey{}).(string); ok {
		return id
	}
	return ""
}

// API bundles the Huma API and the underlying http.ServeMux so main.go can
// start an http.Server against it.
type API struct {
	Huma huma.API
	Mux  *http.ServeMux
}

// New creates the API with logging + recover + CORS middleware applied.
//
// Middleware ordering: requestLog wraps recover so the deferred log line
// runs *after* recover has written the 500 response — that way panicked
// requests still get a log line with the resulting 500 status, not the
// pre-panic 0.
func New(title, version string, logger *slog.Logger, corsOrigins []string) *API {
	mux := http.NewServeMux()
	cfg := huma.DefaultConfig(title, version)
	api := humago.New(mux, cfg)

	api.UseMiddleware(requestLogMiddleware(logger))
	api.UseMiddleware(recoverMiddleware(api, logger))
	api.UseMiddleware(corsMiddleware(corsOrigins))

	RegisterHealth(api)

	return &API{Huma: api, Mux: mux}
}

func recoverMiddleware(api huma.API, logger *slog.Logger) func(huma.Context, func(huma.Context)) {
	return func(ctx huma.Context, next func(huma.Context)) {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("panic recovered",
					"value", r,
					"path", ctx.URL().Path,
					"request_id", RequestID(ctx.Context()),
				)
				_ = huma.WriteErr(api, ctx, http.StatusInternalServerError, "internal error")
			}
		}()
		next(ctx)
	}
}

func requestLogMiddleware(logger *slog.Logger) func(huma.Context, func(huma.Context)) {
	return func(ctx huma.Context, next func(huma.Context)) {
		start := time.Now()
		reqID := uuid.NewString()
		ctx.SetHeader("X-Request-ID", reqID)
		defer func() {
			logger.Info("request",
				"method", ctx.Method(),
				"path", ctx.URL().Path,
				"status", ctx.Status(),
				"duration_ms", time.Since(start).Milliseconds(),
				"request_id", reqID,
			)
		}()
		next(huma.WithValue(ctx, reqIDKey{}, reqID))
	}
}

func corsMiddleware(allowed []string) func(huma.Context, func(huma.Context)) {
	// Normalise the configured allowlist once: trim whitespace and any
	// trailing slash so values pasted with or without a trailing "/" match
	// the browser's Origin header (which never carries one).
	normalisedAllowed := make([]string, 0, len(allowed))
	for _, a := range allowed {
		a = strings.TrimSpace(a)
		a = strings.TrimRight(a, "/")
		if a != "" {
			normalisedAllowed = append(normalisedAllowed, a)
		}
	}

	return func(ctx huma.Context, next func(huma.Context)) {
		origin := strings.TrimRight(ctx.Header("Origin"), "/")
		if origin != "" && slices.Contains(normalisedAllowed, origin) {
			ctx.SetHeader("Access-Control-Allow-Origin", origin)
			ctx.SetHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
			ctx.SetHeader("Access-Control-Allow-Headers", "Content-Type, Authorization")
			ctx.SetHeader("Access-Control-Allow-Credentials", "true")
			ctx.SetHeader("Vary", "Origin")
		}
		if ctx.Method() == http.MethodOptions {
			ctx.SetStatus(http.StatusNoContent)
			return
		}
		next(ctx)
	}
}
