// Package server builds the Huma API, registers platform endpoints, and applies middleware.
package server

import (
	"context"
	"log/slog"
	"net/http"
	"slices"
	"strings"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
	"github.com/google/uuid"
)

// reqIDKey is the per-request context.Value key holding the request ID
// generated by requestLogMiddleware.
type reqIDKey struct{}

// RequestID extracts the request ID set by requestLogMiddleware, or an empty
// string if the middleware did not run.
func RequestID(ctx context.Context) string {
	if id, ok := ctx.Value(reqIDKey{}).(string); ok {
		return id
	}
	return ""
}

// API bundles the Huma API and the underlying http.ServeMux so main.go can
// start an http.Server against it.
type API struct {
	Huma huma.API
	Mux  *http.ServeMux
}

// New creates the API with logging + recover middleware applied to every
// registered Huma operation. CORS is intentionally NOT a Huma middleware —
// see CORS for why; cmd/api wraps the resulting mux with CORS at the
// http.Handler level.
//
// Middleware ordering: requestLog wraps recover so the deferred log line
// runs *after* recover has written the 500 response — that way panicked
// requests still get a log line with the resulting 500 status, not the
// pre-panic 0.
func New(title, version string, logger *slog.Logger) *API {
	mux := http.NewServeMux()
	cfg := huma.DefaultConfig(title, version)

	// Declare the cookie-based session as a security scheme so the OpenAPI
	// spec tells clients how to authenticate. Operations behind RequireAuth
	// reference this scheme via huma.Operation.Security; openapi-typescript
	// surfaces it in the generated FE client.
	if cfg.OpenAPI.Components == nil {
		cfg.OpenAPI.Components = &huma.Components{}
	}
	cfg.OpenAPI.Components.SecuritySchemes = map[string]*huma.SecurityScheme{
		SessionSecurityScheme: {
			Type:        "apiKey",
			In:          "cookie",
			Name:        "session",
			Description: "Session cookie set on /api/auth/signup or /api/auth/login.",
		},
	}

	api := humago.New(mux, cfg)

	api.UseMiddleware(requestLogMiddleware(logger))
	api.UseMiddleware(recoverMiddleware(api, logger))

	RegisterHealth(api)

	return &API{Huma: api, Mux: mux}
}

// SessionSecurityScheme is the OpenAPI key used to reference the session
// cookie scheme from protected operations. Use it via:
//
//	Security: []map[string][]string{{server.SessionSecurityScheme: {}}}
const SessionSecurityScheme = "session"

func recoverMiddleware(api huma.API, logger *slog.Logger) func(huma.Context, func(huma.Context)) {
	return func(ctx huma.Context, next func(huma.Context)) {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("panic recovered",
					"value", r,
					"path", ctx.URL().Path,
					"request_id", RequestID(ctx.Context()),
				)
				_ = huma.WriteErr(api, ctx, http.StatusInternalServerError, "internal error")
			}
		}()
		next(ctx)
	}
}

func requestLogMiddleware(logger *slog.Logger) func(huma.Context, func(huma.Context)) {
	return func(ctx huma.Context, next func(huma.Context)) {
		start := time.Now()
		reqID := uuid.NewString()
		ctx.SetHeader("X-Request-ID", reqID)
		defer func() {
			logger.Info("request",
				"method", ctx.Method(),
				"path", ctx.URL().Path,
				"status", ctx.Status(),
				"duration_ms", time.Since(start).Milliseconds(),
				"request_id", reqID,
			)
		}()
		next(huma.WithValue(ctx, reqIDKey{}, reqID))
	}
}

// CORS returns a stdlib http.Handler middleware that sets CORS headers for
// allowed origins and short-circuits OPTIONS preflights with 204.
//
// It MUST live at the http.Handler level (not as a Huma middleware) because
// Huma middlewares only fire for registered operations. Browser preflights
// arrive as OPTIONS to paths registered for POST/PATCH/DELETE — those aren't
// Huma operations, so a Huma-level CORS middleware never sees them and the
// browser blocks the real request with "no Access-Control-Allow-Origin".
//
// The allowlist is normalised at construction (trim whitespace and trailing
// slash) so the configured value matches the browser's Origin header
// (which never carries a trailing slash).
func CORS(allowed []string) func(http.Handler) http.Handler {
	normalised := make([]string, 0, len(allowed))
	for _, a := range allowed {
		a = strings.TrimSpace(a)
		a = strings.TrimRight(a, "/")
		if a != "" {
			normalised = append(normalised, a)
		}
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			origin := strings.TrimRight(r.Header.Get("Origin"), "/")
			if origin != "" && slices.Contains(normalised, origin) {
				w.Header().Set("Access-Control-Allow-Origin", origin)
				w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
				w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
				w.Header().Set("Access-Control-Allow-Credentials", "true")
				w.Header().Set("Vary", "Origin")
			}
			if r.Method == http.MethodOptions {
				w.WriteHeader(http.StatusNoContent)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}
